// Core configuration defaults (centralized)
export const GAME_CONFIG_DEFAULTS = {
  DEFAULT_SPEED: 1.0,
  DEFAULT_RANDOMNESS: 0.5,
  DEFAULT_SPAWN_RATE: 60,
  DEFAULT_TARGETS_ENABLED: true,
  DEFAULT_FRIENDLIES_ENABLED: true,
  DEFAULT_OBJECT_SIZE: 20,
  DEFAULT_RATIO: 0.5,
  DEFAULT_PLAYER_NAME: 'player 1',
  DEFAULT_TARGET_WORDS: '2 4 6 8 10',
  DEFAULT_FRIENDLY_WORDS: '1 3 5 7 9',
  DEFAULT_TARGET_COLOR: '#C9DBE0', // Columbia blue
  DEFAULT_FRIENDLY_COLOR: '#ECEBDB', // Eggshell
  DEFAULT_CAPTION_COLOR: '#F3EAC9', // Parchment
  DEFAULT_BACKGROUND_COLOR: '#DAE8E3', // Mint cream
  DEFAULT_FRIENDLY_MODE: 'both',
  DEFAULT_SIZE_VARIATION: 0.3,
  DEFAULT_MISS_PENALTY_ENABLED: false,
  DEFAULT_TIME_LIMIT_ENABLED: false,
  DEFAULT_TIME_LIMIT: 120,
  DEFAULT_SCORE_LIMIT_ENABLED: false,
  DEFAULT_SCORE_LIMIT: 50,
  DEFAULT_CAPTION_ENABLED: true,
  DEFAULT_CAPTION_DIRECTION: 'left',
  DEFAULT_CAPTION_COLOR: '#ffffff',
  DEFAULT_CAPTION_SIZE: 18,
  DEFAULT_CAPTION_MAX_TOKENS: 5,
  DEFAULT_VOLUME: 0.5,
  DEFAULT_TARGET_TRANSPARENCY: 1.0,
  DEFAULT_FRIENDLY_TRANSPARENCY: 1.0,
  DEFAULT_FRIENDLY_IMAGES_TRANSPARENCY: 1.0,
  DEFAULT_SHOW_OBJECT_PATHS: false,
  DEFAULT_OBJECT_SHADOWS: false,
  DEFAULT_BACKGROUND_COLOR: '#4444ff',
  BASE_SPEED: 140,
  SPAWN_MARGIN: 50,
  UI: {
    RIGHT_PANEL_WIDTH: 200,
  },
  ASSETS: {
    TARGET_FOLDER: 'assets/target/',
  FRIENDLY_FOLDER: 'assets/images/friendly/',
    SOUNDS_FOLDER: 'assets/sounds/'
  },
};

export function createDefaultGameConfig() {
  const D = GAME_CONFIG_DEFAULTS;
  return {
    speed: D.DEFAULT_SPEED,
    randomness: D.DEFAULT_RANDOMNESS,
    spawnRate: D.DEFAULT_SPAWN_RATE,
    targetsEnabled: D.DEFAULT_TARGETS_ENABLED,
    friendliesEnabled: D.DEFAULT_FRIENDLIES_ENABLED,
    objectSize: D.DEFAULT_OBJECT_SIZE,
    ratio: D.DEFAULT_RATIO,
    playerName: D.DEFAULT_PLAYER_NAME,
    targetWords: D.DEFAULT_TARGET_WORDS,
    friendlyWords: D.DEFAULT_FRIENDLY_WORDS,
    targetColor: D.DEFAULT_TARGET_COLOR,
    friendlyColor: D.DEFAULT_FRIENDLY_COLOR,
    friendlyMode: D.DEFAULT_FRIENDLY_MODE,
    sizeVariation: D.DEFAULT_SIZE_VARIATION,
    missPenaltyEnabled: D.DEFAULT_MISS_PENALTY_ENABLED,
    timeLimitEnabled: D.DEFAULT_TIME_LIMIT_ENABLED,
    timeLimit: D.DEFAULT_TIME_LIMIT,
    scoreLimitEnabled: D.DEFAULT_SCORE_LIMIT_ENABLED,
    scoreLimit: D.DEFAULT_SCORE_LIMIT,
    captionEnabled: D.DEFAULT_CAPTION_ENABLED,
    captionDirection: D.DEFAULT_CAPTION_DIRECTION,
    captionColor: D.DEFAULT_CAPTION_COLOR,
    captionSize: D.DEFAULT_CAPTION_SIZE,
    captionMaxTokens: D.DEFAULT_CAPTION_MAX_TOKENS,
  volume: D.DEFAULT_VOLUME,
    targetTransparency: D.DEFAULT_TARGET_TRANSPARENCY,
    friendlyTransparency: D.DEFAULT_FRIENDLY_TRANSPARENCY,
    friendlyImagesTransparency: D.DEFAULT_FRIENDLY_IMAGES_TRANSPARENCY,
    showObjectPaths: D.DEFAULT_SHOW_OBJECT_PATHS,
    objectShadows: D.DEFAULT_OBJECT_SHADOWS,
    backgroundColor: D.DEFAULT_BACKGROUND_COLOR,
    useRandomColors: false,
  // Theme removed
  };
}
